# Generated by Django 4.1.3 on 2022-11-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_uservoterestaurantmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
