# Generated by Django 4.1.3 on 2022-11-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_restaurantmenuvote_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='food_item',
            field=models.ManyToManyField(blank=True, null=True, to='restaurant.restaurantfooditem'),
        ),
    ]
