# Generated by Django 4.1.3 on 2022-11-12 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('restaurant', '0006_restaurantmenu_food_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoterestaurantmenu',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_vote_restaurant', to='employee.employee'),
        ),
    ]
